// GENERATED by tools/gen_rom_map.py from tools/ms1z_romdata.py.
// Do not edit by hand -- re-run the generator.
//
// Byte base and byte size of every SDRAM region. One board, one layout:
// lomakai and makaiden have the same region sizes.
localparam [23:0] MAIN_BASE = 24'h000000;  localparam [24:0] MAIN_SIZE = 25'h0040000;
localparam [23:0] SND_BASE  = 24'h040000;  localparam [24:0] SND_SIZE  = 25'h0010000;
localparam [23:0] L0_BASE   = 24'h050000;  localparam [24:0] L0_SIZE   = 25'h0020000;
localparam [23:0] L1_BASE   = 24'h070000;  localparam [24:0] L1_SIZE   = 25'h0010000;
localparam [23:0] SPR_BASE  = 24'h080000;  localparam [24:0] SPR_SIZE  = 25'h0020000;
localparam [24:0] TOTAL     = 25'h00A0000;
