#!/usr/bin/env python3
"""Parse MAME's jaleco/megasys1.cpp and emit tools/ms1_romdata.py.

The plan's rule is that the .mra files, the hardware ioctl stream and the
simulation ROM images all come from ONE table (docs/PLAN.md 1.5). This builds
that table mechanically from the driver rather than by hand, because a
seventeen-set transcription of file names, offsets and CRCs is exactly the kind
of work that produces a silent one-character error -- and the region bases it
feeds are the thing NMK16 lost a week to (`23'h8C0000` dropping bit 23).

Re-run it whenever the MAME reference moves; the output is checked in so the
diff is reviewable.

    tools/extract_ms1_roms.py [path/to/megasys1.cpp]
"""
import os, re, sys

SETS = {
    # setname:      (mode, parent or None)
    'avspirit':     ('B', None),
    'monkelf':      ('B', 'avspirit'),
    'edf':          ('B', None),
    'edfa':         ('B', 'edf'),
    'edfb':         ('B', 'edf'),
    'edfu':         ('B', 'edf'),
    'edfbl':        ('B', 'edf'),
    'hayaosi1':     ('B', None),
    '64street':     ('C', None),
    '64streetj':    ('C', '64street'),
    '64streetja':   ('C', '64street'),
    'bigstrik':     ('C', None),
    'chimerab':     ('C', None),
    'chimeraba':    ('C', 'chimerab'),
    'cybattlr':     ('C', None),
    'peekaboo':     ('D', None),
    'peekaboou':    ('D', 'peekaboo'),
}

DEFAULT_SRC = os.path.expanduser('~/mame/src/mame/jaleco/megasys1.cpp')


def parse(src_path):
    src = open(src_path, encoding='utf-8', errors='replace').read()

    # GAME() lines give the description and the rotation
    meta = {}
    for m in re.finditer(r'^GAME\(\s*(\d+),\s*([A-Za-z0-9_]+),\s*([A-Za-z0-9_]+),\s*'
                         r'([A-Za-z0-9_]+),\s*([A-Za-z0-9_]+),\s*([A-Za-z0-9_:]+),\s*'
                         r'([A-Za-z0-9_]+),\s*(ROT\d+),\s*"([^"]*)",\s*"([^"]*)"',
                         src, re.M):
        year, setname, parent, cfg, ports, state, init, rot, mfr, desc = m.groups()
        meta[setname] = dict(year=int(year), cfg=cfg, ports=ports, init=init,
                             rot=int(rot[3:]), manufacturer=mfr, desc=desc)

    out = {}
    for setname, (mode, parent) in SETS.items():
        m = re.search(r'ROM_START\(\s*' + re.escape(setname) + r'\s*\)(.*?)ROM_END', src, re.S)
        if not m:
            raise SystemExit(f'{setname}: no ROM_START found')
        body = m.group(1)

        regions, cur = [], None
        for line in body.splitlines():
            line = re.sub(r'//.*$', '', line).strip()
            if not line:
                continue
            r = re.match(r'ROM_REGION\(\s*(0x[0-9a-fA-F]+|\d+)\s*,\s*"([^"]+)"', line)
            if r:
                cur = dict(name=r.group(2), size=int(r.group(1), 0), parts=[])
                regions.append(cur)
                continue
            # A dump flag may sit between the length and the CRC, and NO_DUMP
            # carries no CRC at all.  Matching only the bare CRC() form drops
            # BAD_DUMP parts silently, which cost chimerab its priority PROM
            # until it was caught -- see docs/known-issues.md MS1-3.
            l = re.match(r'ROM_(LOAD16_BYTE|LOAD)\(\s*"([^"]+)"\s*,\s*'
                         r'(0x[0-9a-fA-F]+|\d+)\s*,\s*(0x[0-9a-fA-F]+|\d+)\s*,\s*'
                         r'(?:(BAD_DUMP|NO_DUMP)\s+)?'
                         r'(?:CRC\(([0-9a-fA-F]+)\)|(NO_DUMP))', line)
            if l and cur is not None:
                form, fname, off, length, flag, crc, bare_nodump = l.groups()
                if bare_nodump:
                    flag, crc = 'NO_DUMP', None
                cur['parts'].append(dict(form=form, name=fname,
                                         offset=int(off, 0), length=int(length, 0),
                                         crc=crc.lower() if crc else None,
                                         flag=(flag or 'OK')))
        if meta.get(setname) is None:
            raise SystemExit(f'{setname}: no GAME() line found')
        out[setname] = dict(mode=mode, parent=parent, regions=regions, **meta[setname])
    return out


def emit(table, path):
    with open(path, 'w') as f:
        f.write('# GENERATED by tools/extract_ms1_roms.py from MAME\'s jaleco/megasys1.cpp.\n'
                '# Do not edit by hand: re-run the extractor so the diff stays reviewable.\n'
                '# One table, three consumers -- the .mra files, the hardware ioctl stream\n'
                '# and the simulation ROM images (docs/PLAN.md 1.5).\n\n'
                'ROMDATA = ')
        import pprint
        pprint.pprint(table, stream=f, width=100, sort_dicts=False)
    print(f'wrote {path}: {len(table)} sets')


if __name__ == '__main__':
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    t = parse(src)
    here = os.path.dirname(os.path.abspath(__file__))
    emit(t, os.path.join(here, 'ms1_romdata.py'))
    for name, e in t.items():
        tot = sum(r['size'] for r in e['regions'])
        print(f"  {name:12} mode {e['mode']}  ROT{e['rot']:<3} {tot/1024/1024:5.2f} MB  "
              f"{len(e['regions'])} regions  {e['desc'][:44]}")
