#!/usr/bin/env python3
"""Extract every DSW1/DSW2 switch for the 17 Mega System 1 B/C/D sets from
MAME itself, and write tools/ms1_dipdata.py.

MAME's own -listxml is the source, not the C++: it already resolves
PORT_INCLUDE, PORT_MODIFY and the COINAGE_8BITS macro, and it marks the
default value. Parsing megasys1.cpp by hand would re-derive all of that and
get it wrong somewhere.

    tools/extract_ms1_dips.py [--mame ~/mame/mame] [--check]

Each switch becomes one MiSTer <dip>:

  * `bits` is a RANGE, "start,end", over the concatenated <switches> bytes:
    DSW1 is bits 0-7 and DSW2 bits 8-15. (NMK16 learned this one the hard
    way -- as "8,9,10,11" a coin field reads as a 2-bit field and shows the
    wrong settings.)
  * `ids` are indexed by the field's RAW value, value 0 first, so a
    2^width-long list with no holes.
  * the `default` bytes come from MAME's own default="yes" markings, which
    is why this also replaces the flat FF,FF the generator used to emit.

GAPS. MAME lists only distinct settings, so a field can have fewer entries
than 2^width. In megasys1 that happens only on the 4-bit Coin A / Coin B,
where the driver's own commented-out lines (megasys1.cpp, COINAGE_8BITS)
show values 1-5 are all 1C_1C -- MAME omits them as duplicates of 0x0f.
Anything else that turns up is filled with "Undefined" and reported, so a
new gap cannot pass silently.
"""
import argparse, os, re, subprocess, sys, xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ms1_romdata as R

OUT = os.path.join(HERE, 'ms1_dipdata.py')
# Bit offset of each port within the concatenated <switches> bytes. Most sets
# split the switches into two 8-bit ports; System D (peekaboo) has one 16-bit
# `DSW` instead, whose low byte is DSW1's byte and high byte DSW2's, so it maps
# at offset 0 with a mask up to 0xFFFF.
TAG_BIT = {'DSW1': 0, 'DSW2': 8, 'DSW': 0}
# megasys1.cpp COINAGE_8BITS: 0x01-0x05 are commented-out duplicates of 1C_1C.
COINAGE_GAP = {'Coin A': '1C_1C', 'Coin B': '1C_1C'}


def width_shift(mask):
    shift = (mask & -mask).bit_length() - 1
    w = (mask >> shift)
    if w & (w + 1):
        raise ValueError(f'mask 0x{mask:X} is not a contiguous field')
    return (w.bit_length(), shift)


def listxml(mame, setname):
    out = subprocess.run([mame, '-listxml', setname], capture_output=True, text=True)
    if out.returncode != 0:
        raise SystemExit(f'{setname}: mame -listxml failed:\n{out.stderr[:400]}')
    return ET.fromstring(out.stdout)


def extract(mame, setname, problems):
    root = listxml(mame, setname)
    dips, default = [], 0xFFFF        # one 16-bit value: low byte DSW1, high DSW2
    for d in root.iter('dipswitch'):
        tag = d.get('tag')
        if tag not in TAG_BIT:
            continue
        mask = int(d.get('mask'))
        width, shift = width_shift(mask)
        vals, dflt = {}, None
        for v in d.iter('dipvalue'):
            idx = (int(v.get('value')) & mask) >> shift
            vals[idx] = v.get('name')
            if v.get('default') == 'yes':
                dflt = idx
        name = d.get('name')
        ids = []
        for i in range(1 << width):
            if i in vals:
                ids.append(vals[i])
            elif name in COINAGE_GAP:
                ids.append(COINAGE_GAP[name])
            else:
                ids.append('Undefined')
                problems.append(f'{setname}: {tag} {name!r} value {i} has no MAME setting')
        if dflt is None:
            dflt = (1 << width) - 1
            problems.append(f'{setname}: {tag} {name!r} has no default; using all-ones')
        lo = TAG_BIT[tag] + shift
        if lo + width > 16:
            raise SystemExit(f'{setname}: {tag} {name!r} runs past bit 15')
        dips.append({'bits': (lo, lo + width - 1), 'name': name, 'ids': ids})
        fld = ((1 << width) - 1) << lo
        default = (default & ~fld) | ((dflt << lo) & fld)
    dips.sort(key=lambda e: e['bits'][0])
    return dips, {'DSW1': default & 0xFF, 'DSW2': (default >> 8) & 0xFF}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--mame', default=os.path.expanduser('~/mame/mame'))
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()

    problems, data = [], {}
    for setname in sorted(R.ROMDATA):
        dips, default = extract(a.mame, setname, problems)
        data[setname] = {'dsw1': default['DSW1'], 'dsw2': default['DSW2'], 'dips': dips}
        print(f'{setname:12s} DSW1={default["DSW1"]:02X} DSW2={default["DSW2"]:02X} '
              f'{len(dips)} switches')

    body = ['# GENERATED by tools/extract_ms1_dips.py from `mame -listxml`.',
            '# Do not edit by hand -- re-run the extractor.',
            '#',
            '# Per set: the DSW1/DSW2 default bytes MAME ships, and one entry per',
            '# switch with its MiSTer bit RANGE and the id list in raw-value order.',
            'DIPDATA = {']
    for setname in sorted(data):
        e = data[setname]
        body.append(f'    {setname!r}: {{')
        body.append(f'        "dsw1": 0x{e["dsw1"]:02X}, "dsw2": 0x{e["dsw2"]:02X},')
        body.append('        "dips": [')
        for d in e['dips']:
            body.append(f'            {{"bits": {d["bits"]!r}, "name": {d["name"]!r},')
            body.append(f'             "ids": {d["ids"]!r}}},')
        body.append('        ],')
        body.append('    },')
    body.append('}')
    text = '\n'.join(body) + '\n'

    if problems:
        print('\nreported:')
        for p in problems:
            print('  ' + p)
    if a.check:
        old = open(OUT).read() if os.path.exists(OUT) else ''
        print('\n' + ('ms1_dipdata.py IS UP TO DATE' if old == text else 'ms1_dipdata.py WOULD CHANGE'))
        return 0 if old == text else 1
    open(OUT, 'w').write(text)
    print(f'\nwrote {OUT}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
