#!/usr/bin/env python3
"""Generate rtl/ms1bcd/ms1bcd_rom_map.vh from tools/ms1_romdata.py.

docs/PLAN.md 1.5 requires the .mra part list, the ioctl stream and the
core's own region bases to come from ONE table. The .mra generator
already derives its layout from ms1_romdata.py; this writes the SAME
layout out as Verilog localparams so the RTL cannot drift from the file
that packs the bytes.

    tools/gen_rom_map.py            # write the header
    tools/gen_rom_map.py --check    # exit 1 if it is out of date
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_ms1bcd_mra as G

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   '..', 'rtl', 'ms1bcd', 'ms1bcd_rom_map.vh')

# The core names regions by function, not by MAME's region name: mode D's
# 'mcu' region occupies the same slot as B/C's 'iomcu'.
SLOT = {'maincpu': 'MAIN', 'audiocpu': 'SND', 'iomcu': 'MCU', 'mcu': 'MCU',
        'scroll1': 'L0', 'scroll2': 'L1', 'scroll3': 'L2',
        'sprites': 'SPR', 'oki1': 'OKI1', 'oki2': 'OKI2'}
SLOTS = ['MAIN', 'SND', 'MCU', 'L0', 'L1', 'L2', 'SPR', 'OKI1', 'OKI2']


def build():
    L = ["// GENERATED by tools/gen_rom_map.py from tools/ms1_romdata.py.",
         "// Do not edit by hand -- re-run the generator.",
         "//",
         "// Byte base and byte size of every SDRAM region, per game mode.",
         "// A region a mode does not have is given base 0 and size 0; the",
         "// core must never fetch from it (mode D has no sound 68000, no",
         "// third scroll layer and no second OKI).",
         ""]
    for mode, mi in (('B', 0), ('C', 1), ('D', 2)):
        lay, tot = G.layout(mode)
        pos = {SLOT[rn]: (base, size) for (rn, size, base) in lay}
        L.append(f"// ---- mode {mode}: {tot} bytes ({tot/1048576:.2f} MB), "
                 f"sets: {', '.join(G.mode_sets(mode))}")
        for s in SLOTS:
            base, size = pos.get(s, (0, 0))
            L.append(f"localparam [23:0] {s}_BASE_{mode} = 24'h{base:06X};"
                     f"  localparam [24:0] {s}_SIZE_{mode} = 25'h{size:07X};")
        L.append(f"localparam [24:0] TOTAL_{mode} = 25'h{tot:07X};")
        L.append("")
    # runtime selection by the mode input
    L.append("// Selected by the core's `mode` input (0 = B, 1 = C, 2 = D).")
    for s in SLOTS:
        L.append(f"wire [23:0] {s}_BASE = (mode == 2'd0) ? {s}_BASE_B :"
                 f" (mode == 2'd1) ? {s}_BASE_C : {s}_BASE_D;")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    text = build()
    if '--check' in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ''
        if cur != text:
            print('ms1bcd_rom_map.vh is out of date; re-run tools/gen_rom_map.py')
            return 1
        print('ms1bcd_rom_map.vh is up to date')
        return 0
    open(OUT, 'w').write(text)
    print(f'wrote {os.path.relpath(OUT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
